
import React, { useState } from 'react';
import { useAccounting } from '../context/AccountingContext';
import { ScrollText, Printer, Download, BookDashed, Hash, Calendar, X } from 'lucide-react';

const JournalLogView: React.FC = () => {
  const { entries } = useAccounting();
  const [dateFilter, setDateFilter] = useState('');

  const filteredEntries = dateFilter 
    ? entries.filter(e => e.date.startsWith(dateFilter))
    : entries;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadCSV = () => {
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Txn ID,Date,Particulars,Debit,Credit\n";

    filteredEntries.forEach(entry => {
      // Debits
      entry.lines.filter(l => l.type === 'DEBIT').forEach(l => {
        csvContent += `${entry.transactionId || ''},${new Date(entry.date).toLocaleDateString()},"${l.accountName} Dr.",${l.amount},""\n`;
      });
      // Credits
      entry.lines.filter(l => l.type === 'CREDIT').forEach(l => {
        csvContent += `${entry.transactionId || ''},${new Date(entry.date).toLocaleDateString()},"To ${l.accountName}","",${l.amount}\n`;
      });
      // Narration
      csvContent += `,"${new Date(entry.date).toLocaleDateString()}","(Being ${entry.narration})","",""\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "journal_daybook.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="h-full w-full bg-[#050b14] overflow-y-auto p-8 font-sans print:bg-white print:text-black print:overflow-visible">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4 print:hidden">
        <div>
          <h2 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-amber-600 tracking-tight flex items-center gap-3">
            <ScrollText className="text-yellow-400" /> Journal Daybook
          </h2>
          <p className="text-gray-400 text-sm mt-1">
             Complete record of posted entries in chronological order.
          </p>
        </div>
        
        <div className="flex flex-wrap gap-3 items-center">
           {/* Date Filter */}
           <div className="relative flex items-center">
             <div className="absolute left-3 text-gray-500"><Calendar size={14}/></div>
             <input 
               type="date" 
               value={dateFilter}
               onChange={(e) => setDateFilter(e.target.value)}
               className="bg-slate-900 border border-gray-700 rounded-xl py-2 pl-9 pr-8 text-sm text-white outline-none focus:border-yellow-500/50"
             />
             {dateFilter && (
               <button onClick={() => setDateFilter('')} className="absolute right-2 text-gray-500 hover:text-white">
                 <X size={14} />
               </button>
             )}
           </div>

           <button 
             onClick={handlePrint}
             className="flex items-center gap-2 px-4 py-2 rounded-xl border border-gray-700 hover:bg-white/5 text-gray-300 transition-all text-sm"
           >
             <Printer size={16} /> Print View
           </button>
           <button 
             onClick={handleDownloadCSV}
             className="flex items-center gap-2 px-4 py-2 rounded-xl bg-yellow-500/10 border border-yellow-500/30 text-yellow-500 hover:bg-yellow-500/20 transition-all shadow-[0_0_15px_rgba(234,179,8,0.1)] text-sm"
           >
             <Download size={16} /> CSV
           </button>
        </div>
      </div>

      {/* Print Header */}
      <div className="hidden print:block mb-8 text-center border-b pb-4 border-black">
        <h1 className="text-2xl font-bold uppercase">Journal Book</h1>
        <p className="text-sm">Generated by ACCT-IDE {dateFilter ? `for ${new Date(dateFilter).toLocaleDateString()}` : ''}</p>
      </div>

      {/* Main Table */}
      <div className="bg-slate-900 border border-glass-border rounded-xl shadow-2xl overflow-hidden print:bg-transparent print:border-black print:shadow-none">
        
        {/* Table Head */}
        <div className="grid grid-cols-12 bg-white/5 border-b border-glass-border p-3 text-xs font-bold text-gray-400 uppercase tracking-widest print:text-black print:border-black print:bg-gray-100">
          <div className="col-span-1 pl-2">Txn #</div>
          <div className="col-span-2">Date</div>
          <div className="col-span-5">Particulars</div>
          <div className="col-span-1 text-center">L.F.</div>
          <div className="col-span-1 text-center">Debit (₹)</div>
          <div className="col-span-2 text-center">Credit (₹)</div>
        </div>

        {/* Table Body */}
        {filteredEntries.length === 0 ? (
          <div className="flex flex-col items-center justify-center p-20 text-gray-500 print:hidden">
            <BookDashed size={48} className="mb-4 opacity-50" />
            <p>{dateFilter ? 'No entries found for selected date.' : 'No Entries Posted Yet'}</p>
          </div>
        ) : (
          <div className="print:text-black">
            {filteredEntries.map((entry) => {
               // Sort lines: Debits first, then Credits
               const debits = entry.lines.filter(l => l.type === 'DEBIT');
               const credits = entry.lines.filter(l => l.type === 'CREDIT');

               return (
                 <div key={entry.id} className="border-b border-white/5 hover:bg-white/5 transition-colors print:border-gray-300">
                   {/* Date & ID Column - Only shown on first row of entry for visual cleanness */}
                   <div className="grid grid-cols-12 text-sm p-3 gap-y-1">
                      
                      {/* Debit Rows */}
                      {debits.map((line, idx) => (
                        <React.Fragment key={line.id}>
                          <div className="col-span-1 font-mono text-neon-blue text-xs pt-1 print:text-black">
                             {idx === 0 ? (entry.transactionId || '#') : ''}
                          </div>
                          <div className="col-span-2 text-gray-400 font-mono text-xs pt-1 print:text-black">
                             {idx === 0 ? new Date(entry.date).toLocaleDateString() : ''}
                          </div>
                          <div className="col-span-5 font-medium text-gray-200 print:text-black">
                             {line.accountName} <span className="ml-4 font-normal text-gray-500 italic print:text-black">...Dr</span>
                          </div>
                          <div className="col-span-1"></div>
                          <div className="col-span-1 text-right font-mono text-gray-300 print:text-black">{line.amount.toFixed(2)}</div>
                          <div className="col-span-2"></div>
                        </React.Fragment>
                      ))}

                      {/* Credit Rows */}
                      {credits.map((line) => (
                        <React.Fragment key={line.id}>
                          <div className="col-span-1"></div>
                          <div className="col-span-2"></div>
                          <div className="col-span-5 font-medium text-gray-200 pl-8 print:text-black">
                             To {line.accountName}
                          </div>
                          <div className="col-span-1"></div>
                          <div className="col-span-1"></div>
                          <div className="col-span-2 text-right font-mono text-gray-300 print:text-black">{line.amount.toFixed(2)}</div>
                        </React.Fragment>
                      ))}

                      {/* Narration Row */}
                      <div className="col-span-3"></div>
                      <div className="col-span-5 text-xs text-gray-500 italic pl-8 mt-1 print:text-gray-600">
                        (Being {entry.narration})
                      </div>
                      <div className="col-span-4"></div>
                   </div>
                 </div>
               );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default JournalLogView;
